print("Гpyna 4")
text_file = open("D:\students4.txt", "wt")
text_file.write("Юля Тушкевич, 0 балів\n")
text_file.write("Оля Дашкевич, 0 балів\n")
text_file.write("Жужа Лермонтов, 0 балів\n")
text_file.write("Саша Прокопов, 0 балів\n")
text_file.close()

print("Гpyna 5")
text_file = open("D:\students5.txt", "wt")
text_file.write("Макс Тушкевич, 0 балів\n")
text_file.write("Данило Дашкевич, 0 балів\n")
text_file.write("Олексій Лермонтов, 0 балів\n")
text_file.write("Женя Прокопов, 0 балів\n")
text_file.close()

print("Гpyna 6")
text_file = open("D:\students6.txt", "wt")
text_file.write("Карбівничий Володимир, 0 балів\n")
text_file.write("Данило Дашкевич, 0 балів\n")
text_file.write("Роман Жуков, 0 балів\n")
text_file.write("Вікторія Трипільська, 0 балів\n")
text_file.close()